### ISSUE TITLE
consider building as an HTML editor?

### ISSUE THREAD

**Issue by dcsan** [fr33mind/Belle#10]
sure this is not going to happen, but thought i'd post anyway:

it would be much more accessible for others to hack on if you were to consider building this as an html5 app. you could still bundle it as a desktop app, but could also provide a web based editor for people to collaboratively build stories...

**Comment by fr33mind** [comment]
Hi,
Sorry for not answering sooner. I see your point, i have thought about that myself, although for some other reasons. However doing something like that now would be, at least in part, like starting over and i can't afford to do that right now.

Can you explain why it would be more accessible to hack on if this was an HTML5 app?
For a collaborative work it's still possible to build stories collaboratively with a desktop app, it doesn't need to be a full HTML5 app.

**Comment by dcsan** [comment]
i think if it was built as a JS app it would be easier to find other people to contribute (or heaven help us, PHP...)

i guess you can have "client server" apps which use native tech on the desktop and connect to a server, but that kind of code in C++ just seems extremely time consuming to write... and very few people have bandwidth to do it for OSS projects?

**Comment by fr33mind** [comment]
Well the engine is a JS app, only the editor is C++. But i don't think having a JS-only app would bring more developers, at least not in a significant way, because if you look at for example WebStory engine it has very few contributors. 
I'm not sure, Qt framework eases lots of things, including networking. But yes, C++ is usually more time consuming to write, but has the performance advantage.
What do you mean people don't have bandwidth for OSS projects?

**Comment by dcsan** [comment]
i guess from a c++ dev's POV it's plenty accessible but i see it a bit differently! 
it just seems that unless there's a reason, there's little benefit to desktop apps for the extra complexity.
good luck with the project, hopefully it will gain some momentum!
