### ISSUE TITLE
Visual novel fragment

### ISSUE THREAD

**Issue by jahnocli** [fr33mind/Belle#27]
[novelFragment1.zip](https://github.com/fr33mind/Belle/files/3276211/novelFragment1.zip)
Thought some people may be interested in this test fragment of a visual novel. This is not my artwork - it is from a graphic novel called "Muktuk Wolfsbreath" (really) by someone called Terry LaBan. I had to fight Belle all the way to get this to work...
I really like the Novelty interface and was excited to find Belle, but it really still needs a lot of work. Hope it's still being developed.
John Oakley

**Comment by fr33mind** [comment]
Thanks for your comment. Can you expand on "I had to fight Belle all the way to get this to work..."? Did you find a bug? If so, what was it? Or it was something else?

Regarding the project, it's basically dead. But anyone is free to continue it, it's open source. My idea with this project was to build some sort of community, where we could build something together, but that didn't work out.

**Comment by jahnocli** [comment]
Hi Carlos,
The interface LOOKS intuitive, but I can tell you that as a new user it is
anything but. I have used Novelty in the past, and I liked that interface,
so I felt encouraged to try this out, as I wanted a browser solution. On
numerous occasions I had to ignore what was on the screen and just guess
what was happening. I found ways of making things work, but it involved
blundering around until I found something that worked by chance (eg,
dialogue box placement), and then copying that to other scenes. If I hadn't
been determined, I would just have given up. Some good tutorials would be
really helpful; the "demo" on the web site is pitiful, and doesn't even
work when it is downloaded.

Anyway, if the project is dead, I don't know what use this feedback will
be. Thanks for what you have done, but I'm no software developer, so I
guess I'll have to keep on looking.
Regards,
John Oakley

**Comment by fr33mind** [comment]
Hello,
Thanks for your feedback. You say it's not intuitive and that's your opinion, no problem. However i also had people say otherwise and to me it looks and is intuitive. Sure you'll still have to learn some things and adapt a bit, but saying it's not intuitive to me it's just not true.
Apparently you came from a Novelty background and maybe you were expecting it was all the same, but it isn't, so being used to how things work on Novelty and then using Belle most likely gave you that bad perception that Belle isn't intuitive. It's just like you said it LOOKS intuitive because it looks like something you're used to, but it's not because it works somewhat differently. Also the fact that Novelty has some good documentation is probably part of the reason you liked the interface to begin with.

But i agree with you, Belle needed some good tutorials and the demo is old, but i don't know what you mean by "doesn't even work when it is downloaded". But guess what, you may not be a software developer, but you can perfectly create some good tutorials and a decent demo, right? However you probably aren't going to do that, like many other people. It's just easier to come here and say it's "pitiful" and then expect that i do everything for you for free. Well, that's part of the reason i won't waste anymore of my free time on this. And, by the way, you know what's also pitiful? Your feedback, it's very vague regarding the problems you found, you barely give any suggestions for improvement. So, yea, feedback goes both ways.

Anyway good luck, keep looking.

**Comment by jahnocli** [comment]
I downloaded the demo, and I couldn't get it to work. Not at all. There's nothing ambiguous about that, it's not just my opinion, it didn't work. And why would I put some effort into developing tutorials for software that is dead (in your words)? Or suggestions for improvement? You seem very defensive -- I'm guessing that no-one asked you to develop this software, but you gave up at some arbitrary point. I see a lot of suggestions for improvement in this forum, but, for instance, the software still has no UNDO feature - there's one suggestion that is way overdue.

If I didn't care I wouldn't have said anything.

**Comment by fr33mind** [comment]
First of all, stop twisting what i've said. I never said your opinion of the demo not working was just your opinion and it worked perfectly. I even said that it was old but i still don't know what you mean by "not working", it's very vague. What do you mean by that? What didn't work? Was playing the demo or was editing the demo? I'm not saying you didn't have problems, i just have no clue what you're talking about.

So you're telling me if i told you now that i would continue the project, you would make some good tutorials and a good demo? Sorry, i don't believe that. Nothing you said so far made me think you were really interested in contributing to this project.

I'm very defensive about what? I just explained what the situation was.

Regarding the UNDO feature, to you is way overdue, but i haven't had many requests for it, maybe once, so i kept postponing it. It's convenient to have but you can live well without it.

Anyway, i believe you care, for your own selfish reasons.

**Comment by jahnocli** [comment]
Okay, let's take some of the heat out of this conversation. Get a friend to download the demo onto a windows machine, unzip it, and double-click on the index.html file. That little gnu character didn't appear on my machine. I think you'll agree that characters are important in a visual novel. I tried to edit the file with the latest issue of Belle, and I couldn't access the files. That's what I mean by "not working". I don't believe that is vague.
Every other piece of software I've ever used, no matter how insignificant, had an UNDO feature. Maybe you only ever had one other request about it, but that doesn't mean it's not a worthy feature.
I've had an academic career and worked on several high-profile eLearning projects. I'm certainly capable of producing a good tutorial for this software.. But if it's dead, (your words, not mine) there doesn't seem to be much point, is all I'm saying.

**Comment by fr33mind** [comment]
Alright, now you were much more clear about what wasn't working in the demo, thank you. But i don't know why we're coming back to the demo, i've said from the beginning that it's an old demo, so i can imagine it having some problems.

Regarding the UNDO feature, i agree with you, it's a worthy feature to have, but like i said, nobody really requested it, instead i got requests for other features. I was also focusing on the core features first, basically having a usable and stable software and then focus on the features that are not really essential, but still important to have, like the UNDO.

I understand that if a project is dead there's no point in contributing, sure. What i was saying was that if it wasn't dead i don't believe you would produce any tutorial for this project. That is simply because from the first moment you came here, the impression i got was that you didn't want to waste any more time with this project and that's fine, but don't pretend you really wanted to contribute. But maybe i'm wrong about you, if so i'm sorry. Anyway, it doesn't matter, no point in arguing about a non issue.

**Comment by jahnocli** [comment]
I really like the software. My first contribution to this 'forum' was to show a short experimental piece I'd made with Belle, (which you haven't commented on, by the way!) and to remark that this process was a lot harder than I had expected. I said I hoped it was still being developed. From there, this whole thread seems to have escalated into personal attacks -- this wasn't what I had in mind.
I'll make a personal pledge to you right now. If there is proof that you or someone else is continuing with the development of the program, I'd be happy to make a tutorial based on my experiences with Belle so far.

**Comment by fr33mind** [comment]
Yes, i didn't comment on it, sorry, but i played it when you first commented. It looks nice, but it's short. Anyway thanks for doing it. I can understand if you had some difficulties working with Belle that would've taken some time to do.
One thing i noticed is that the dialogues (bubbles) are all images and you used a character to do that, which is very clever, but using simple images and hiding and showing them, i think it would be more  straightforward for a beginner. But your solution is much more elegant, no doubt, just maybe harder to find out at first, i guess.

Regarding the software, there's no one interested in working on it, as far as i know. However if you want you can make a tutorial. But i understand that if there isn't more development it doesn't make much sense in making a tutorial, so don't worry about it. Thanks anyway.

**Comment by fr33mind** [comment]
Since there aren't any more comments, i'm closing this issue. Anything else let me know.

**Comment by jahnocli** [comment]
Will do. Thanks.
